// <auto-generated />
using System;
using BotConstructor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BotConstructor.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BotConstructor.Core.Entities.EmailConfirmationToken", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<DateTime>("ExpiresAt").HasColumnType("datetime(6)");
                b.Property<bool>("IsUsed").HasColumnType("tinyint(1)");
                b.Property<string>("Token").IsRequired().HasMaxLength(255).HasColumnType("varchar(255)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime(6)");
                b.Property<DateTime?>("UsedAt").HasColumnType("datetime(6)");
                b.Property<int>("UserId").HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("ExpiresAt");
                b.HasIndex("Token").IsUnique();
                b.HasIndex("UserId");
                b.ToTable("EmailConfirmationTokens");
            });

            modelBuilder.Entity("BotConstructor.Core.Entities.LoginAttempt", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<string>("Email").IsRequired().HasMaxLength(255).HasColumnType("varchar(255)");
                b.Property<string>("FailureReason").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<string>("IpAddress").IsRequired().HasMaxLength(45).HasColumnType("varchar(45)");
                b.Property<bool>("IsSuccessful").HasColumnType("tinyint(1)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime(6)");
                b.Property<string>("UserAgent").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<int?>("UserId").HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("CreatedAt");
                b.HasIndex("Email");
                b.HasIndex("UserId");
                b.ToTable("LoginAttempts");
            });

            modelBuilder.Entity("BotConstructor.Core.Entities.PasswordResetToken", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<DateTime>("ExpiresAt").HasColumnType("datetime(6)");
                b.Property<string>("IpAddress").HasMaxLength(45).HasColumnType("varchar(45)");
                b.Property<bool>("IsUsed").HasColumnType("tinyint(1)");
                b.Property<string>("Token").IsRequired().HasMaxLength(255).HasColumnType("varchar(255)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime(6)");
                b.Property<DateTime?>("UsedAt").HasColumnType("datetime(6)");
                b.Property<int>("UserId").HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("ExpiresAt");
                b.HasIndex("Token").IsUnique();
                b.HasIndex("UserId");
                b.ToTable("PasswordResetTokens");
            });

            modelBuilder.Entity("BotConstructor.Core.Entities.Role", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<bool>("IsSystemRole").HasColumnType("tinyint(1)");
                b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("varchar(50)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime(6)");

                b.HasKey("Id");
                b.HasIndex("Name").IsUnique();
                b.ToTable("Roles");

                b.HasData(
                    new { Id = 1, CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), Description = "Владелец платформы", IsSystemRole = true, Name = "SuperAdmin" },
                    new { Id = 2, CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), Description = "Администратор", IsSystemRole = true, Name = "Admin" },
                    new { Id = 3, CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), Description = "Обычный пользователь", IsSystemRole = true, Name = "User" },
                    new { Id = 4, CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), Description = "Разработчик шаблонов", IsSystemRole = true, Name = "Developer" },
                    new { Id = 5, CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), Description = "Реферальщик", IsSystemRole = true, Name = "Affiliate" });
            });

            modelBuilder.Entity("BotConstructor.Core.Entities.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime?>("BlockedAt").HasColumnType("datetime(6)");
                b.Property<string>("BlockedReason").HasColumnType("longtext");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<string>("Email").IsRequired().HasMaxLength(255).HasColumnType("varchar(255)");
                b.Property<bool>("EmailConfirmed").HasColumnType("tinyint(1)");
                b.Property<DateTime?>("EmailConfirmedAt").HasColumnType("datetime(6)");
                b.Property<int>("FailedLoginAttempts").HasColumnType("int");
                b.Property<string>("FirstName").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<bool>("IsActive").HasColumnType("tinyint(1)");
                b.Property<bool>("IsBlocked").HasColumnType("tinyint(1)");
                b.Property<DateTime?>("LastLoginAt").HasColumnType("datetime(6)");
                b.Property<string>("LastLoginIp").HasColumnType("longtext");
                b.Property<string>("LastName").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<DateTime?>("LockedOutUntil").HasColumnType("datetime(6)");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(255).HasColumnType("varchar(255)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime(6)");

                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("BotConstructor.Core.Entities.UserExternalLogin", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<string>("Provider").IsRequired().HasMaxLength(50).HasColumnType("varchar(50)");
                b.Property<string>("ProviderDisplayName").HasMaxLength(255).HasColumnType("varchar(255)");
                b.Property<string>("ProviderKey").IsRequired().HasMaxLength(255).HasColumnType("varchar(255)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime(6)");
                b.Property<int>("UserId").HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("UserId");
                b.HasIndex("Provider", "ProviderKey").IsUnique();
                b.ToTable("UserExternalLogins");
            });

            modelBuilder.Entity("BotConstructor.Core.Entities.UserRole", b =>
            {
                b.Property<int>("UserId").HasColumnType("int");
                b.Property<int>("RoleId").HasColumnType("int");
                b.Property<DateTime>("AssignedAt").HasColumnType("datetime(6)");

                b.HasKey("UserId", "RoleId");
                b.HasIndex("RoleId");
                b.ToTable("UserRoles");
            });

            modelBuilder.Entity("BotConstructor.Core.Entities.UserSession", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<DateTime>("ExpiresAt").HasColumnType("datetime(6)");
                b.Property<string>("IpAddress").IsRequired().HasMaxLength(45).HasColumnType("varchar(45)");
                b.Property<bool>("IsActive").HasColumnType("tinyint(1)");
                b.Property<string>("SessionId").IsRequired().HasMaxLength(255).HasColumnType("varchar(255)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime(6)");
                b.Property<string>("UserAgent").HasMaxLength(500).HasColumnType("varchar(500)");
                b.Property<int>("UserId").HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("ExpiresAt");
                b.HasIndex("SessionId").IsUnique();
                b.HasIndex("UserId");
                b.ToTable("UserSessions");
            });

            modelBuilder.Entity("BotConstructor.Core.Entities.UserSettings", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<string>("Language").IsRequired().HasMaxLength(10).HasColumnType("varchar(10)");
                b.Property<string>("TimeZone").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<bool>("TwoFactorEnabled").HasColumnType("tinyint(1)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime(6)");
                b.Property<int>("UserId").HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("UserId").IsUnique();
                b.ToTable("UserSettings");
            });

            modelBuilder.Entity("BotConstructor.Core.Entities.EmailConfirmationToken", b =>
            {
                b.HasOne("BotConstructor.Core.Entities.User", "User")
                    .WithMany("EmailConfirmationTokens")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("BotConstructor.Core.Entities.LoginAttempt", b =>
            {
                b.HasOne("BotConstructor.Core.Entities.User", "User")
                    .WithMany("LoginAttempts")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.SetNull);
                b.Navigation("User");
            });

            modelBuilder.Entity("BotConstructor.Core.Entities.PasswordResetToken", b =>
            {
                b.HasOne("BotConstructor.Core.Entities.User", "User")
                    .WithMany("PasswordResetTokens")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("BotConstructor.Core.Entities.UserExternalLogin", b =>
            {
                b.HasOne("BotConstructor.Core.Entities.User", "User")
                    .WithMany("ExternalLogins")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("BotConstructor.Core.Entities.UserRole", b =>
            {
                b.HasOne("BotConstructor.Core.Entities.Role", "Role")
                    .WithMany("UserRoles")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("BotConstructor.Core.Entities.User", "User")
                    .WithMany("UserRoles")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Role");
                b.Navigation("User");
            });

            modelBuilder.Entity("BotConstructor.Core.Entities.UserSession", b =>
            {
                b.HasOne("BotConstructor.Core.Entities.User", "User")
                    .WithMany("UserSessions")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("BotConstructor.Core.Entities.UserSettings", b =>
            {
                b.HasOne("BotConstructor.Core.Entities.User", "User")
                    .WithOne("UserSettings")
                    .HasForeignKey("BotConstructor.Core.Entities.UserSettings", "UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("BotConstructor.Core.Entities.Role", b =>
            {
                b.Navigation("UserRoles");
            });

            modelBuilder.Entity("BotConstructor.Core.Entities.User", b =>
            {
                b.Navigation("EmailConfirmationTokens");
                b.Navigation("ExternalLogins");
                b.Navigation("LoginAttempts");
                b.Navigation("PasswordResetTokens");
                b.Navigation("UserRoles");
                b.Navigation("UserSessions");
                b.Navigation("UserSettings");
            });
#pragma warning restore 612, 618
        }
    }
}
